# Site settings
title: EIS Lab
email: jobregon@seoultech.ac.kr
description: Homepage of the Explainable Intelligent Systems Lab at SeoulTech
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  EIS Lab<br/>
  Prof. Josue Obregon<br/>
  SeoulTech

location: >
  Seoul National University of Science and Technology<br/>
  232 Gongneung-ro, Nowon-gu<br/>
  Seoul, Republic of Korea

contact: >
  <a href="mailto:jobregon@seoultech.ac.kr" target="_blank" style="color:CornflowerBlue"><i class="fa fa-envelope fa-1x" style="color:CornflowerBlue"></i> Contact lab PI via email</a> <br/>
  <a href="https://github.com/st-eislab/st-eislab.github.io" style="color:CornflowerBlue"><i class="fa fa-github fa-1x" style="color:CornflowerBlue"></i> Use this site as a template. </a>

# Pages shown in navbar
nav_pages:    
  - name: members
  - name: research
  - name: publications  
  - name: teaching


include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: obregon2024.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
